version: '3.3'
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - '3000:3000'
      depends_on:
        - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'omni_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
# Names our volume
volumes:
  my-db:
    driver: local